FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
#COPY ["AwesomeWeather/AwesomeWeather.csproj", "AwesomeWeather/"]
COPY ["AwesomeWeather.WeatherForecast.Api.csproj", "AwesomeWeather.WeatherForecast.Api/"]
RUN dotnet restore "AwesomeWeather.WeatherForecast.Api/AwesomeWeather.WeatherForecast.Api.csproj"
COPY . .
WORKDIR "/src/AwesomeWeather.WeatherForecast.Api"
RUN dotnet build "AwesomeWeather.WeatherForecast.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN apt-get update -yq \
    && apt-get install curl gnupg -yq \
    && curl -sL https://deb.nodesource.com/setup_14.x | bash \
    && apt-get install nodejs -yq
RUN dotnet publish "AwesomeWeather.WeatherForecast.Api.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "AwesomeWeather.WeatherForecast.Api.dll"]
